# Generated by Django 3.1.1 on 2020-09-30 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200929_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='m_type',
        ),
    ]
