# Generated by Django 3.1.1 on 2020-09-30 19:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_remove_message_m_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='gid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
